
#type: args

train:
  epochs: 100
  batch_size: 64
  lr: 1.0e-3

diffusion:
  layers: 4
  channels: 64
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  time_layer:
    type: "bilstm" or "longformer" or "transformer" or None
    nheads: 8
    hidden_size: 64
    attention_window: 32
  spatial_layer:
    type: 'diffconv' or 'transformer' or None
    nheads: 8
    hidden_size: 64
    adj: './data/adj_matrix_soilmoisture.npy'
    order: 1

model:
  is_unconditional: 0
  timeemb: 32
  featureemb: 16
  target_strategy: "random"
  missing_pattern: 'random' or 'space_block' or 'time_block' or 'block' or 'prediction'
